version: '3'
networks:
  sra-local:
    driver: bridge
services:
    mongodb:
        image: mongo:latest
        ports: 
          - "27017:27017"
        container_name: sra-mongo
        hostname: sra-local
        networks: 
          - sra-local
        
        
        